<div class="center">
    <h1 class="form-header">Register</h1>
    <form method="POST" action="/register/submit">
        <input class="input-form" type="email" placeholder="Your Email" name="email" required>
        <input class="input-form" type="text" placeholder="Your Desired Username" name="username" required>
        <input class="input-form" type="password" placeholder="Your Desired Password" name="password" required>
        <button class="submit" type="submit">Register</button>
    </form>
</div>