<h3>Register on Industry Tool V2</h3>
<div id="register">
    <form method="POST" action="/register/submit">
        <div>
            <label for="email">Your Email:</label>
            <input type="email" placeholder="Your Desired Email" name="email" required>
        </div>
        <div>
            <label for="username">Your Username:</label>
            <input type="text" placeholder="Your Desired Username" name="username" required>
        </div>
        <div>
            <label for="password">Your Password:</label>
            <input type="password" placeholder="Your Desired Password" name="password" required>
        </div>
        <div>
            <button type="submit">Register</button>
        </div>
    </form>
</div>