<div class="settings-panel">
    <h1 id="content-header">Api Key Management</h1>
    <form method="POST" action="settings/save">
        <div class="row">
            <label for="keyid">Key ID:</label>
            <input type="text" name="keyid" id="keyid" value="<?php echo isset($this->keyID) ? $this->keyID : '' ?>" required>
        </div>
        <div class="row">
            <label for="verCode">Verification Code:</label>
            <input type="text" name="verCode" id="verCode" value="<?php echo isset($this->verificationCode) ? $this->verificationCode : '' ?>" required>
        </div>
        <div class="row">
            <button id="btn-submit" class="btn-left" type="submit" disabled>Save</button>
        </div>
        <div class="row">
            <button id="btn-verify" class="btn-right">Verify</button>
        </div>
        <input type="hidden" name="characterId">
        <input type="hidden" name="characterName">
    </form>
</div>
