<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Industry Tool V2</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="favicon.png">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/industrytool.css">
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="container">
    <header>
        <nav>
            <ul>
                <li>
                    <a href="/" target="_top" <?php echo $_SESSION['active'] == 'home' ?  "class='active'"  : ''; ?>>Home</a>
                </li>
                <li>
                    <a href="/about" target="_top" <?php echo $_SESSION['active'] == 'about' ?  "class='active'"  : ''; ?>>About</a>
                </li>
                <li>
                    <a href="/contact" target="_top" <?php echo $_SESSION['active'] == 'contact' ?  "class='active'"  : ''; ?>>Contact</a>
                </li>
                <?php if (!isset($_SESSION['user'])): ?>
                    <li>
                        <a href="/login" target="_top">Login</a>
                    </li>
                <?php else: ?>
                    <li>
                        <a href="/logout" target="_top">Logout</a>
                    </li>
                <?php endif; ?>
                <?php if ($_SESSION['role'] == 'admin' || $_SESSION['role'] == 'owner'): ?>
                    <li>
                        <a href="/admin" <?php echo $_SESSION['active'] == 'admin' ?  "class='active'"  : ''; ?>>Admin</a>
                    </li>
                <?php endif; ?>
                <li class="welcome">
                    <p>Welcome, <?php echo isset($_SESSION['user']) ? $_SESSION['user'] . '!' : 'guest!'; ?></p>
                </li>
            </ul>
        </nav>
    </header>

    <?php echo $this->_html; ?>

</div>

</body>
</html>
