<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/industrytool.css">
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="container">
    <header>
        <nav>
            <ul>
                <li>
                    <a href="/" target="_top">Home</a>
                </li>
                <li>
                    <a href="/about" target="_top">About</a>
                </li>
                <li>
                    <a href="/contact" target="_top">Contact</a>
                </li>
                <li>
                    <a href="/login" target="_top">Login</a>
                </li>
                <li class="welcome">
                    <p>Welcome, guest!</p>
                </li>
            </ul>
        </nav>
    </header>

    <?php echo $this->_html; ?>

</div>

</body>
</html>
