<div id="passwordReset">
    <form method="POST" action="/recover/reset">
        <div>
            <label for="password">Your New Password:</label>
            <input type="password" placeholder="Your Desired New Password" name="password" required>
        </div>
        <div>
            <button type="submit">Submit</button>
            <input type="hidden" value="<?php echo $this->uid ?>" name="uid">
        </div>
    </form>
</div>