<div class="login">
    <h1>Login</h1>
    <form method="POST" action="/login/submit">
        <input type="text" placeholder="Username" name="username" required>
        <input type="password" placeholder="Password" name="password" required>
        <button type="submit" id="login-btn">Login</button>
        <div>
            <a href="/login/forgot">Forgot password?</a>
            <a href="/register">Register</a>
        </div>
    </form>
</div>