<div class="login center">
    <h1 class="form-header">Login</h1>
    <form method="POST" action="/login/submit">
        <input class="input-form" type="text" placeholder="Username" name="username" required>
        <input class="input-form" type="password" placeholder="Password" name="password" required>
        <button class="submit" type="submit" id="login-btn">Login</button>
        <div class="form-bottom">
            <a class="btn-left" href="/login/forgot">Forgot password?</a>
            <a class="btn-right" href="/register">Register</a>
        </div>
    </form>
</div>